# Generated by Django 5.2.5 on 2025-09-03 15:11

import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('body_text', models.TextField()),
                ('slug', models.CharField(max_length=16)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.AlterModelManagers(
            name='wlmathuser',
            managers=[
                ('objects', web.models.WlmathUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='wlmathuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='wlmathuser',
            name='last_name',
        ),
    ]
