# Generated by Django 5.2.5 on 2025-09-05 15:06

import web.markdown
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='body_text',
        ),
        migrations.AddField(
            model_name='problem',
            name='body',
            field=web.markdown.MartorField(default=''),
            preserve_default=False,
        ),
    ]
