# Generated by Django 5.2.5 on 2025-09-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wlmathuser',
            name='bio',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
