# Generated by Django 5.2.5 on 2025-09-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_problem_body_text_problem_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='category',
        ),
    ]
