# Generated by Django 5.2.5 on 2025-09-03 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_problem_alter_wlmathuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
