# Generated by Django 5.2.5 on 2025-09-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_tag_remove_problem_category_problem_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='wlmathuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
