# Generated by Django 5.2.5 on 2025-09-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_problem_date_added_problem_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
