# Generated by Django 5.2.5 on 2025-09-11 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_problem_body_text_problem_body'),
        ('web', '0003_wlmathuser_bio'),
    ]

    operations = [
    ]
