# Generated by Django 5.2.5 on 2025-09-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_problem_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='wlmathuser',
            name='problems_solved',
            field=models.ManyToManyField(to='web.problem'),
        ),
    ]
