# Generated by Django 5.2.5 on 2025-09-14 21:01

import web.markdown
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_merge_20250910_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=100)),
                ('content_markdown', web.markdown.MartorField()),
            ],
        ),
        migrations.AlterField(
            model_name='wlmathuser',
            name='bio',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
