# Generated by Django 5.2.5 on 2025-09-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_upcomingcontest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('links', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
