# Generated by Django 5.2.5 on 2025-09-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitedata',
            name='data_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='wlmathuser',
            name='problems_solved',
            field=models.ManyToManyField(related_name='solved_users', to='web.problem'),
        ),
    ]
