# Generated by Django 5.2.5 on 2025-09-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_websitedata_alter_wlmathuser_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('date', models.DateField()),
                ('registration_link', models.CharField()),
                ('registration_open', models.BooleanField(default=False)),
                ('contest_link', models.CharField()),
            ],
        ),
    ]
