# Generated by Django 5.2.5 on 2025-09-28 04:37

import web.markdown
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_websitedata_data_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_edit_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField()),
                ('content', web.markdown.MartorField()),
            ],
        ),
    ]
