# Generated by Django 5.2.5 on 2025-10-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_tag_color'),
        ('web', '0016_announcement'),
    ]

    operations = [
    ]
